apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kafka
    helm:
      values: |-
        kraft:
          enabled: true
        service:
          replicaCount: 3
{{/*        externalAccess:*/}}
{{/*          service:*/}}
{{/*            type: LoadBalancer*/}}
{{/*            ports:*/}}
{{/*              external: 9094*/}}
{{/*          enabled: true*/}}
{{/*          autoDiscovery:*/}}
{{/*            enabled: true*/}}
{{/*        enabled: true*/}}
        rbac:
          create: true
        fullnameOverride: "kafka"
        livenessProbe:
          enabled: true
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
          periodSeconds: 30
          successThreshold: 1
        readinessProbe:
          enabled: true
          initialDelaySeconds: 5
          failureThreshold: 10
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
        listeners:
          client:
            containerPort: 9092
            protocol: PLAINTEXT
            name: CLIENT
            sslClientAuth: ""
          controller:
            name: CONTROLLER
            containerPort: 9093
            protocol: PLAINTEXT
            sslClientAuth: ""
          interbroker:
            containerPort: 9094
            protocol: PLAINTEXT
            name: INTERNAL
            sslClientAuth: ""
{{/*          external:*/}}
{{/*            containerPort: 9095*/}}
{{/*            protocol: PLAINTEXT*/}}
{{/*            name: EXTERNAL*/}}
{{/*            sslClientAuth: ""*/}}
        kraft:
          enabled: true
        zookeeper:
          enabled: false
        rbac:
          create: true
        controller:
          automountServiceAccountToken: true
        broker:
          automountServiceAccountToken: true
        zookeeper:
          enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s